l_english:
 global_edicts_commander_trade_config_events.1.t: "Advanced Configuration Settings"
 global_edicts_commander_trade_config_events.1.d: "You can control which trade nodes are included or excluded when applying the Protect Trade state edict. States that are within a §RDisabled§! trade node will not have the edict applied to them."
 global_edicts_commander_trade_config_events.1.a: "Enable All Trade Nodes"
 global_edicts_commander_trade_config_events.1.b: "Disable All Trade Nodes"
 global_edicts_commander_trade_config_events.1.c: "Configure Europe's Trade Nodes: [edict_commander_europe_trade_flags_status_loc]"
 global_edicts_commander_trade_config_events.1.dee: "Configure Asia's Trade Nodes: [edict_commander_asia_trade_flags_status_loc]"
 global_edicts_commander_trade_config_events.1.e: "Configure Africa's Trade Node: [edict_commander_africa_trade_flags_status_loc]"
 global_edicts_commander_trade_config_events.1.f: "Configure North America's Trade Nodes: [edict_commander_north_america_trade_flags_status_loc]"
 global_edicts_commander_trade_config_events.1.g: "Configure South America's Trade Nodes: [edict_commander_south_america_trade_flags_status_loc]"
 global_edicts_commander_trade_config_events.1.h: "Configure Oceanias Trade Nodes: [edict_commander_oceania_trade_flags_status_loc]"
 global_edicts_commander_trade_config_events.1.back: "Go Back"
 
 
 global_edicts_commander_trade_config_events.2.t: "Configure European Trade Nodes"
 global_edicts_commander_trade_config_events.2.a: "Enable All (Europe)"
 global_edicts_commander_trade_config_events.2.b: "Disable All (Europe)"
 global_edicts_commander_trade_config_events.2.opt_english_channel: "English Channel: [edict_commander_english_channel_loc]"
 global_edicts_commander_trade_config_events.2.opt_champagne: "Champagne: [edict_commander_champagne_loc]"
 global_edicts_commander_trade_config_events.2.opt_north_sea: "North Sea: [edict_commander_north_sea_loc]"
 global_edicts_commander_trade_config_events.2.opt_lubeck: "Lubeck: [edict_commander_lubeck_loc]"
 global_edicts_commander_trade_config_events.2.opt_baltic_sea: "Baltic Sea: [edict_commander_baltic_sea_loc]"
 global_edicts_commander_trade_config_events.2.opt_bordeaux: "Bordeaux: [edict_commander_bordeaux_loc]"
 global_edicts_commander_trade_config_events.2.opt_sevilla: "Cordoba: [edict_commander_sevilla_loc]"
 global_edicts_commander_trade_config_events.2.opt_valencia: "Valencia: [edict_commander_valencia_loc]"
 global_edicts_commander_trade_config_events.2.opt_genoa: "Genoa: [edict_commander_genoa_loc]"
 global_edicts_commander_trade_config_events.2.opt_venice: "Venice: [edict_commander_venice_loc]"
 global_edicts_commander_trade_config_events.2.opt_wien: "Danube: [edict_commander_wien_loc]"
 global_edicts_commander_trade_config_events.2.opt_ragusa: "Ragusa: [edict_commander_ragusa_loc]"
 global_edicts_commander_trade_config_events.2.opt_rheinland: "Rheinland: [edict_commander_rheinland_loc]"
 global_edicts_commander_trade_config_events.2.opt_saxony: "Saxony: [edict_commander_saxony_loc]"
 global_edicts_commander_trade_config_events.2.opt_krakow: "Krakow: [edict_commander_krakow_loc]"
 global_edicts_commander_trade_config_events.2.opt_pest: "Carpathia: [edict_commander_pest_loc]"
 global_edicts_commander_trade_config_events.2.opt_constantinople: "Constantinople: [edict_commander_constantinople_loc]"
 global_edicts_commander_trade_config_events.2.opt_kiev: "Kiev: [edict_commander_kiev_loc]"
 global_edicts_commander_trade_config_events.2.opt_crimea: "Crimea: [edict_commander_crimea_loc]"
 global_edicts_commander_trade_config_events.2.opt_novgorod: "Novgorod: [edict_commander_novgorod_loc]"
 global_edicts_commander_trade_config_events.2.opt_white_sea: "White Sea: [edict_commander_white_sea_loc]"
 global_edicts_commander_trade_config_events.2.opt_kazan: "Kazan: [edict_commander_kazan_loc]"
 global_edicts_commander_trade_config_events.2.opt_astrakhan: "Astrakhan: [edict_commander_astrakhan_loc]"
 global_edicts_commander_trade_config_events.2.back: "Go Back"

 
 global_edicts_commander_trade_config_events.3.t: "Configure Asian Trade Nodes"

 global_edicts_commander_trade_config_events.3.back: "Go Back"
 global_edicts_commander_trade_config_events.3.a: "Enable All (Asia)"
 global_edicts_commander_trade_config_events.3.b: "Disable All (Asia)"

 global_edicts_commander_trade_config_events.3.opt_samarkand: "Samarkand: [edict_commander_samarkand_loc]"
 global_edicts_commander_trade_config_events.3.opt_aleppo: "Aleppo: [edict_commander_aleppo_loc]"
 global_edicts_commander_trade_config_events.3.opt_basra: "Basra: [edict_commander_basra_loc]"
 global_edicts_commander_trade_config_events.3.opt_persia: "Persia: [edict_commander_persia_loc]"
 global_edicts_commander_trade_config_events.3.opt_hormuz: "Hormuz: [edict_commander_hormuz_loc]"
 global_edicts_commander_trade_config_events.3.opt_lahore: "Lahore: [edict_commander_lahore_loc]"
 global_edicts_commander_trade_config_events.3.opt_gujarat: "Gujarat: [edict_commander_gujarat_loc]"
 global_edicts_commander_trade_config_events.3.opt_doab: "Doab: [edict_commander_doab_loc]"
 global_edicts_commander_trade_config_events.3.opt_deccan: "Deccan: [edict_commander_deccan_loc]"
 global_edicts_commander_trade_config_events.3.opt_coromandel: "Coromandel: [edict_commander_coromandel_loc]"
 global_edicts_commander_trade_config_events.3.opt_bengal: "Bengal: [edict_commander_bengal_loc]"
 global_edicts_commander_trade_config_events.3.opt_burma: "Burma: [edict_commander_burma_loc]"
 global_edicts_commander_trade_config_events.3.opt_siam: "Siam: [edict_commander_siam_loc]"
 global_edicts_commander_trade_config_events.3.opt_malacca: "Malacca: [edict_commander_malacca_loc]"
 global_edicts_commander_trade_config_events.3.opt_the_moluccas: "The Moluccas: [edict_commander_the_moluccas_loc]"
 global_edicts_commander_trade_config_events.3.opt_philippines: "Philippines: [edict_commander_philippines_loc]"
 global_edicts_commander_trade_config_events.3.opt_siberia: "Siberia: [edict_commander_siberia_loc]"
 global_edicts_commander_trade_config_events.3.opt_yumen: "Yumen: [edict_commander_yumen_loc]"
 global_edicts_commander_trade_config_events.3.opt_girin: "Girin: [edict_commander_girin_loc]"
 global_edicts_commander_trade_config_events.3.opt_nippon: "Nippon: [edict_commander_nippon_loc]"
 global_edicts_commander_trade_config_events.3.opt_beijing: "Beijing: [edict_commander_beijing_loc]"
 global_edicts_commander_trade_config_events.3.opt_xian: "Xi'an: [edict_commander_xian_loc]"
 global_edicts_commander_trade_config_events.3.opt_hangzhou: "Hangzhou: [edict_commander_hangzhou_loc]"
 global_edicts_commander_trade_config_events.3.opt_canton: "Canton: [edict_commander_canton_loc]"
 global_edicts_commander_trade_config_events.3.opt_chengdu: "Chengdu: [edict_commander_chengdu_loc]"
 global_edicts_commander_trade_config_events.3.opt_lhasa: "Lhasa: [edict_commander_lhasa_loc]"

 global_edicts_commander_trade_config_events.4.t: "Configure African Trade Nodes"

 global_edicts_commander_trade_config_events.4.back: "Go Back"
 global_edicts_commander_trade_config_events.4.a: "Enable All (Africa)"
 global_edicts_commander_trade_config_events.4.b: "Disable All (Africa)"

 global_edicts_commander_trade_config_events.4.opt_alexandria: "Alexandria: [edict_commander_alexandria_loc]"
 global_edicts_commander_trade_config_events.4.opt_tunis: "Tunis: [edict_commander_tunis_loc]"
 global_edicts_commander_trade_config_events.4.opt_safi: "Safi: [edict_commander_safi_loc]"
 global_edicts_commander_trade_config_events.4.opt_ivory_coast: "Ivory Coast: [edict_commander_ivory_coast_loc]"
 global_edicts_commander_trade_config_events.4.opt_timbuktu: "Timbuktu: [edict_commander_timbuktu_loc]"
 global_edicts_commander_trade_config_events.4.opt_katsina: "Katsina: [edict_commander_katsina_loc]"
 global_edicts_commander_trade_config_events.4.opt_ethiopia: "Ethiopia: [edict_commander_ethiopia_loc]"
 global_edicts_commander_trade_config_events.4.opt_gulf_of_aden: "Gulf of Aden: [edict_commander_gulf_of_aden_loc]"
 global_edicts_commander_trade_config_events.4.opt_zanzibar: "Zanzibar: [edict_commander_zanzibar_loc]"
 global_edicts_commander_trade_config_events.4.opt_great_lakes: "Great Lakes: [edict_commander_great_lakes_loc]"
 global_edicts_commander_trade_config_events.4.opt_congo: "Congo: [edict_commander_congo_loc]"
 global_edicts_commander_trade_config_events.4.opt_zambezi: "Zambezi: [edict_commander_zambezi_loc]"
 global_edicts_commander_trade_config_events.4.opt_cape_of_good_hope: "Cape of Good Hope: [edict_commander_cape_of_good_hope_loc]"

 global_edicts_commander_trade_config_events.5.t: "Configure North American Trade Nodes"
 global_edicts_commander_trade_config_events.5.back: "Go Back"

 global_edicts_commander_trade_config_events.5.a: "Enable All (North America)"
 global_edicts_commander_trade_config_events.5.b: "Disable All (North America)"

 global_edicts_commander_trade_config_events.5.opt_california: "California: [edict_commander_california_loc]"
 global_edicts_commander_trade_config_events.5.opt_hudson_bay: "Hudson Bay: [edict_commander_hudson_bay_loc]"
 global_edicts_commander_trade_config_events.5.opt_gulf_of_st_lawrence: "Gulf of St. Lawrence: [edict_commander_gulf_of_st_lawrence_loc]"
 global_edicts_commander_trade_config_events.5.opt_mississippi_river: "Mississippi River: [edict_commander_mississippi_river_loc]"
 global_edicts_commander_trade_config_events.5.opt_ohio: "Ohio: [edict_commander_ohio_loc]"
 global_edicts_commander_trade_config_events.5.opt_chesapeake: "Chesapeake Bay: [edict_commander_chesapeake_loc]"
 global_edicts_commander_trade_config_events.5.opt_rio_grande: "Rio Grande: [edict_commander_rio_grande_loc]"
 global_edicts_commander_trade_config_events.5.opt_mexico: "Mexico: [edict_commander_mexico_loc]"
 global_edicts_commander_trade_config_events.5.opt_caribbean: "Caribbean: [edict_commander_caribbean_loc]"
 global_edicts_commander_trade_config_events.5.opt_panama: "Panama: [edict_commander_panama_loc]"

 global_edicts_commander_trade_config_events.6.t: "Configure South American Trade Nodes"
 global_edicts_commander_trade_config_events.6.back: "Go Back"

 global_edicts_commander_trade_config_events.6.a: "Enable All (South America)"
 global_edicts_commander_trade_config_events.6.b: "Disable All (South America)"

 global_edicts_commander_trade_config_events.6.opt_lima: "Lima: [edict_commander_lima_loc]"
 global_edicts_commander_trade_config_events.6.opt_amazonas: "Amazonas: [edict_commander_amazonas_loc]"
 global_edicts_commander_trade_config_events.6.opt_cuiba: "Cuiaba: [edict_commander_cuiba_loc]"
 global_edicts_commander_trade_config_events.6.opt_brazil: "Brazil: [edict_commander_brazil_loc]"
 global_edicts_commander_trade_config_events.6.opt_rio_de_la_plata: "Rio de la Plata: [edict_commander_rio_de_la_plata_loc]"
 global_edicts_commander_trade_config_events.6.opt_patagonia: "Patagonia: [edict_commander_patagonia_loc]"

 global_edicts_commander_trade_config_events.7.t: "Configure Oceanian Trade Nodes"
 global_edicts_commander_trade_config_events.7.back: "Go Back"

 global_edicts_commander_trade_config_events.7.a: "Enable All (Oceania)"
 global_edicts_commander_trade_config_events.7.b: "Disable All (Oceania)"

 global_edicts_commander_trade_config_events.7.opt_australia: "Australia: [edict_commander_australia_loc]"
 global_edicts_commander_trade_config_events.7.opt_polynesian_triangle: "Polynesian Triangle: [edict_commander_polynesian_triangle_loc]"