l_english:
 global_edicts_commander_movement_config_events.1.t: "Advanced French Infrastructure Network Settings"
 global_edicts_commander_movement_config_events.1.d: "Manage which regions are affected by the French Infrastructure Network edict. Select a continent to configure its regions individually, or use the global options below. The status indicates if all, some, or none of the regions within a continent are currently enabled."

 global_edicts_commander_movement_config_events.1.back: "Back" 
 global_edicts_commander_movement_config_events.1.enable_all_regions: "Enable All Regions Globally"
 global_edicts_commander_movement_config_events.1.disable_all_regions: "Disable All Regions Globally"

 global_edicts_commander_movement_config_events.1.europe_region: "Europe: [edict_commander_europe_movement_flags_status_loc]"
 global_edicts_commander_movement_config_events.1.asia_region: "Asia: [edict_commander_asia_movement_flags_status_loc]"
 global_edicts_commander_movement_config_events.1.africa_region: "Africa: [edict_commander_africa_movement_flags_status_loc]"
 global_edicts_commander_movement_config_events.1.north_america_region: "North America: [edict_commander_north_america_movement_flags_status_loc]"
 global_edicts_commander_movement_config_events.1.south_america_region: "South America: [edict_commander_south_america_movement_flags_status_loc]"
 global_edicts_commander_movement_config_events.1.oceania_region: "Oceania: [edict_commander_oceania_movement_flags_status_loc]"

 global_edicts_commander_movement_config_events.2.t: "Europe"
 global_edicts_commander_movement_config_events.2.d: "Select European regions to toggle the French Infrastructure Network edict. The current status (Enabled/Disabled) for each region is shown."

 global_edicts_commander_movement_config_events.2.back: "Back to Main Menu"
 global_edicts_commander_movement_config_events.2.enable_all_regions: "Enable All European Regions"
 global_edicts_commander_movement_config_events.2.disable_all_regions: "Disable All European Regions"

 global_edicts_commander_movement_config_events.2.france: "France: [edict_commander_france_loc]"
 global_edicts_commander_movement_config_events.2.low_countries: "Low Countries: [edict_commander_low_countries_loc]"
 global_edicts_commander_movement_config_events.2.south_german: "South Germany: [edict_commander_south_german_loc]"
 global_edicts_commander_movement_config_events.2.north_german: "North Germany: [edict_commander_north_german_loc]"
 global_edicts_commander_movement_config_events.2.british_isles: "Britain: [edict_commander_british_isles_loc]"
 global_edicts_commander_movement_config_events.2.iberia: "Iberia: [edict_commander_iberia_loc]"
 global_edicts_commander_movement_config_events.2.italy: "Italy: [edict_commander_italy_loc]"
 global_edicts_commander_movement_config_events.2.carpathia: "Carpathia: [edict_commander_carpathia_loc]"
 global_edicts_commander_movement_config_events.2.balkan: "Balkans: [edict_commander_balkan_loc]"
 global_edicts_commander_movement_config_events.2.poland: "Poland: [edict_commander_poland_loc]"
 global_edicts_commander_movement_config_events.2.baltic: "Baltic: [edict_commander_baltic_loc]"
 global_edicts_commander_movement_config_events.2.scandinavia: "Scandinavia: [edict_commander_scandinavia_loc]"
 global_edicts_commander_movement_config_events.2.ruthenia: "Ruthenia: [edict_commander_ruthenia_loc]"
 global_edicts_commander_movement_config_events.2.crimea: "Pontic Steppe: [edict_commander_crimea_loc]"
 global_edicts_commander_movement_config_events.2.russia: "Russia: [edict_commander_russia_loc]"
 global_edicts_commander_movement_config_events.2.ural: "Ural: [edict_commander_ural_loc]"
 global_edicts_commander_movement_config_events.2.anatolia: "Anatolia: [edict_commander_anatolia_loc]"
 global_edicts_commander_movement_config_events.2.caucasia: "Caucasia: [edict_commander_caucasia_loc]"

 global_edicts_commander_movement_config_events.3.t: "Asia"
 global_edicts_commander_movement_config_events.3.d: "Select Asian regions to toggle the French Infrastructure Network edict. The current status (Enabled/Disabled) for each region is shown."

 global_edicts_commander_movement_config_events.3.back: "Back to Main Menu"
 global_edicts_commander_movement_config_events.3.enable_all_regions: "Enable All Asian Regions"
 global_edicts_commander_movement_config_events.3.disable_all_regions: "Disable All Asian Regions"

 global_edicts_commander_movement_config_events.3.arabia: "Arabia: [edict_commander_arabia_loc]"
 global_edicts_commander_movement_config_events.3.bengal: "Bengal: [edict_commander_bengal_loc]"
 global_edicts_commander_movement_config_events.3.burma: "Burma: [edict_commander_burma_loc]"
 global_edicts_commander_movement_config_events.3.central_asia: "Central Asia: [edict_commander_central_asia_loc]"
 global_edicts_commander_movement_config_events.3.coromandel: "Coromandel: [edict_commander_coromandel_loc]"
 global_edicts_commander_movement_config_events.3.deccan: "Deccan: [edict_commander_deccan_loc]"
 global_edicts_commander_movement_config_events.3.east_siberia: "East Siberia: [edict_commander_east_siberia_loc]"
 global_edicts_commander_movement_config_events.3.hindusthan: "Hindustan: [edict_commander_hindusthan_loc]"
 global_edicts_commander_movement_config_events.3.indo_china: "Indochina: [edict_commander_indo_china_loc]"
 global_edicts_commander_movement_config_events.3.indonesia: "Indonesia: [edict_commander_indonesia_loc]"
 global_edicts_commander_movement_config_events.3.japan: "Japan: [edict_commander_japan_loc]"
 global_edicts_commander_movement_config_events.3.khorasan: "Khorasan: [edict_commander_khorasan_loc]"
 global_edicts_commander_movement_config_events.3.korea: "Korea: [edict_commander_korea_loc]"
 global_edicts_commander_movement_config_events.3.malaya: "Malaya: [edict_commander_malaya_loc]"
 global_edicts_commander_movement_config_events.3.manchuria: "Manchuria: [edict_commander_manchuria_loc]"
 global_edicts_commander_movement_config_events.3.mashriq: "Mashriq: [edict_commander_mashriq_loc]"
 global_edicts_commander_movement_config_events.3.moluccas: "Moluccas: [edict_commander_moluccas_loc]"
 global_edicts_commander_movement_config_events.3.mongolia: "Mongolia: [edict_commander_mongolia_loc]"
 global_edicts_commander_movement_config_events.3.north_china: "North China: [edict_commander_north_china_loc]"
 global_edicts_commander_movement_config_events.3.persia: "Persia: [edict_commander_persia_loc]"
 global_edicts_commander_movement_config_events.3.south_china: "South China: [edict_commander_south_china_loc]"
 global_edicts_commander_movement_config_events.3.tibet: "Tibet: [edict_commander_tibet_loc]"
 global_edicts_commander_movement_config_events.3.west_india: "West India: [edict_commander_west_india_loc]"
 global_edicts_commander_movement_config_events.3.west_siberia: "West Siberia: [edict_commander_west_siberia_loc]"
 global_edicts_commander_movement_config_events.3.xinan: "Xinan: [edict_commander_xinan_loc]"


 global_edicts_commander_movement_config_events.4.t: "Africa"
 global_edicts_commander_movement_config_events.4.d: "Select African regions to toggle the French Infrastructure Network edict. The current status (Enabled/Disabled) for each region is shown."


 global_edicts_commander_movement_config_events.4.back: "Back to Main Menu"
 global_edicts_commander_movement_config_events.4.enable_all_regions: "Enable All African Regions"
 global_edicts_commander_movement_config_events.4.disable_all_regions: "Disable All African Regions"

 global_edicts_commander_movement_config_events.4.central_africa: "Central Africa: [edict_commander_central_africa_loc]"
 global_edicts_commander_movement_config_events.4.east_africa: "East Africa: [edict_commander_east_africa_loc]"
 global_edicts_commander_movement_config_events.4.egypt: "Egypt: [edict_commander_egypt_loc]"
 global_edicts_commander_movement_config_events.4.guinea: "Guinea: [edict_commander_guinea_loc]"
 global_edicts_commander_movement_config_events.4.horn_of_africa: "Horn of Africa: [edict_commander_horn_of_africa_loc]"
 global_edicts_commander_movement_config_events.4.kongo: "Congo: [edict_commander_kongo_loc]"
 global_edicts_commander_movement_config_events.4.maghreb: "Maghreb: [edict_commander_maghreb_loc]"
 global_edicts_commander_movement_config_events.4.niger: "Niger: [edict_commander_niger_loc]"
 global_edicts_commander_movement_config_events.4.sahel: "Sahel: [edict_commander_sahel_loc]"
 global_edicts_commander_movement_config_events.4.south_africa: "South Africa: [edict_commander_south_africa_loc]"

 global_edicts_commander_movement_config_events.5.t: "North America"
 global_edicts_commander_movement_config_events.5.d: "Select North American regions (including Central America and the Caribbean) to toggle the French Infrastructure Network edict. The current status (Enabled/Disabled) for each region is shown."


 global_edicts_commander_movement_config_events.5.back: "Back to Main Menu"
 global_edicts_commander_movement_config_events.5.enable_all_regions: "Enable All North American Regions"
 global_edicts_commander_movement_config_events.5.disable_all_regions: "Disable All North American Regions"

 global_edicts_commander_movement_config_events.5.california: "California: [edict_commander_california_loc]"
 global_edicts_commander_movement_config_events.5.canada: "Canada: [edict_commander_canada_loc]"
 global_edicts_commander_movement_config_events.5.carribeans: "Caribbean: [edict_commander_carribeans_loc]"
 global_edicts_commander_movement_config_events.5.cascadia: "Cascadia: [edict_commander_cascadia_loc]"
 global_edicts_commander_movement_config_events.5.central_america: "Central America: [edict_commander_central_america_loc]"
 global_edicts_commander_movement_config_events.5.great_lakes: "Great Lakes: [edict_commander_great_lakes_loc]"
 global_edicts_commander_movement_config_events.5.great_plains: "Great Plains: [edict_commander_great_plains_loc]"
 global_edicts_commander_movement_config_events.5.hudson_bay: "Hudson Bay: [edict_commander_hudson_bay_loc]"
 global_edicts_commander_movement_config_events.5.mexico: "Mexico: [edict_commander_mexico_loc]"
 global_edicts_commander_movement_config_events.5.mississippi: "Mississippi: [edict_commander_mississippi_loc]"
 global_edicts_commander_movement_config_events.5.northeast_america: "Northeast: [edict_commander_northeast_america_loc]"
 global_edicts_commander_movement_config_events.5.rio_grande: "Rio Grande: [edict_commander_rio_grande_loc]"
 global_edicts_commander_movement_config_events.5.southeast_america: "Southeast: [edict_commander_southeast_america_loc]"
 global_edicts_commander_movement_config_events.5.random_new_world: "Random New World: [edict_commander_random_new_world_loc]"

 global_edicts_commander_movement_config_events.6.t: "South America"
 global_edicts_commander_movement_config_events.6.d: "Select South American regions to toggle the French Infrastructure Network edict. The current status (Enabled/Disabled) for each region is shown."

 global_edicts_commander_movement_config_events.6.back: "Back to Main Menu"
 global_edicts_commander_movement_config_events.6.enable_all_regions: "Enable All South American Regions"
 global_edicts_commander_movement_config_events.6.disable_all_regions: "Disable All South American Regions"

 global_edicts_commander_movement_config_events.6.brazil: "Brazil: [edict_commander_brazil_loc]"
 global_edicts_commander_movement_config_events.6.colombia: "Colombia: [edict_commander_colombia_loc]"
 global_edicts_commander_movement_config_events.6.la_plata: "La Plata: [edict_commander_la_plata_loc]"
 global_edicts_commander_movement_config_events.6.peru: "Peru: [edict_commander_peru_loc]"
 global_edicts_commander_movement_config_events.6.upper_peru: "Upper Peru: [edict_commander_upper_peru_loc]"

 global_edicts_commander_movement_config_events.7.t: "Oceania"
 global_edicts_commander_movement_config_events.7.d: "Select Oceanian regions to toggle the French Infrastructure Network edict. The current status (Enabled/Disabled) for each region is shown."

 global_edicts_commander_movement_config_events.7.back: "Back to Main Menu"
 global_edicts_commander_movement_config_events.7.enable_all_regions: "Enable All Oceanian Regions"
 global_edicts_commander_movement_config_events.7.disable_all_regions: "Disable All Oceanian Regions"

 global_edicts_commander_movement_config_events.7.australia: "Australia: [edict_commander_australia_loc]"
 global_edicts_commander_movement_config_events.7.oceanea: "Oceania: [edict_commander_oceanea_loc]"